In [11]:
import pandas as pd

In [12]:
REPORT_PATH = "../../data/results/"

In [13]:
forest_test_200_data = pd.read_csv(REPORT_PATH + "forest-test_200.csv")
forest_test_200_data.head(20)

,description,rmse,rmse_variance,mse,mse_variance,r2,r2_variance,num_records_analyzed,time
0,"Random Forest Regression, where n_estimators=25",1.9673,0.5504,4.1731,2.2666,0.8678,0.0604,200,12/08/21 06:45:46
1,"Random Forest Regression, where n_estimators=50",1.9125,0.5166,3.9246,2.2108,0.8813,0.0277,200,12/08/21 06:45:50
2,"Random Forest Regression, where n_estimators=100",1.9009,0.5819,3.9519,2.4721,0.8843,0.0299,200,12/08/21 06:45:53
3,"Random Forest Regression, where n_estimators=150",1.8891,0.5056,3.8244,1.9968,0.8826,0.0363,200,12/08/21 06:45:57
4,"Random Forest Regression, where n_estimators=200",1.9023,0.5105,3.8792,2.0480,0.8817,0.0329,200,12/08/21 06:46:01
5,"Random Forest Regression, where n_estimators=250",1.8905,0.5240,3.8487,2.1517,0.8834,0.0330,200,12/08/21 06:46:06
6,"Random Forest Regression, where n_estimators=300",1.9094,0.5062,3.9021,2.0391,0.8806,0.0339,200,12/08/21 06:46:11
7,"Random Forest Regression, where n_estimators=350",1.9250,0.5738,4.0350,2.4240,0.8794,0.0375,200,12/08/21 06:46:16

In [14]:
forest_test_4011_data = pd.read_csv(REPORT_PATH + "forest-test_4011.csv")
forest_test_4011_data.head(200)

,description,rmse,rmse_variance,mse,mse_variance,r2,r2_variance,num_records_analyzed,time
0,"Random Forest Regression, where n_estimators=25",0.7934,0.0763,0.6353,0.1155,0.9821,0.0024,4011,12/08/21 06:47:38
1,"Random Forest Regression, where n_estimators=50",0.8050,0.0601,0.6516,0.0927,0.9816,0.0016,4011,12/08/21 06:47:45
2,"Random Forest Regression, where n_estimators=100",0.7813,0.0649,0.6147,0.0971,0.9827,0.0018,4011,12/08/21 06:47:55
3,"Random Forest Regression, where n_estimators=150",0.7919,0.0760,0.6329,0.1155,0.9822,0.0023,4011,12/08/21 06:48:08
4,"Random Forest Regression, where n_estimators=200",0.7920,0.0705,0.6322,0.1068,0.9822,0.0021,4011,12/08/21 06:48:24
5,"Random Forest Regression, where n_estimators=250",0.7938,0.0698,0.6350,0.1056,0.9821,0.0021,4011,12/08/21 06:48:44
6,"Random Forest Regression, where n_estimators=300",0.7862,0.0682,0.6228,0.1020,0.9825,0.0021,4011,12/08/21 06:49:08
7,"Random Forest Regression, where n_estimators=350",0.7838,0.0725,0.6196,0.1082,0.9826,0.0022,4011,12/08/21 06:49:34

In [15]:
k_test_results_200_data = pd.read_csv(REPORT_PATH + "k-test-results_200.csv")
k_test_results_200_data.head(200)

,description,rmse,rmse_variance,mse,mse_variance,r2,r2_variance,num_records_analyzed,time
0,"KNN Regressor, where K = 1",3.0416,0.6953,9.7350,4.2872,0.6790,0.1309,200,12/08/21 06:35:50
1,"KNN Regressor, where K = 2",3.0341,0.8948,10.0062,4.9744,0.6800,0.1682,200,12/08/21 06:35:53
2,"KNN Regressor, where K = 3",2.8754,0.9360,9.1439,5.0326,0.7133,0.1556,200,12/08/21 06:35:56
3,"KNN Regressor, where K = 4",2.8586,0.7835,8.7853,4.0419,0.7184,0.1341,200,12/08/21 06:35:59
4,"KNN Regressor, where K = 5",2.9796,0.7419,9.4286,4.4576,0.7005,0.1141,200,12/08/21 06:36:03
5,"KNN Regressor, where K = 6",2.9434,0.8263,9.3463,4.9494,0.7079,0.1225,200,12/08/21 06:36:06
6,"KNN Regressor, where K = 7",2.8734,0.8391,8.9606,5.0858,0.7184,0.1314,200,12/08/21 06:36:09
7,"KNN Regressor, where K = 8",2.9270,0.8751,9.3331,5.4598,0.7110,0.1272,200,12/08/21 06:36:12
8,"KNN Regressor, where K = 9",3.0105,0.9698,10.0038,6.2036,0.6935,0.1457,200,12/08/21 06:36:15
9,"KNN Regressor, where K = 10",3.0636,0.9965,10.3785,6.5165,0.6818,0.1549,200,12/08/21 06:36:18
10,"KNN Regressor, where K = 11",3.0666,1.0148,10.4340,6.8170,0.6869,0.1365,200,12/08/21 06:36:21
11,"KNN Regressor, where K = 12",3.1286,1.0380,10.8653,7.1934,0.6781,0.1277,200,12/08/21 06:36:24
12,"KNN Regressor, where K = 13",3.1837,1.0337,11.2043,7.2490,0.6677,0.1256,200,12/08/21 06:36:27
13,"KNN Regressor, where K = 14",3.2517,1.0598,11.6964,7.6421,0.6560,0.1218,200,12/08/21 06:36:30
14,"KNN Regressor, where K = 15",3.3016,1.1311,12.1802,8.1366,0.6461,0.1328,200,12/08/21 06:36:33
15,"KNN Regressor, where K = 16",3.3909,1.1349,12.7863,8.2696,0.6271,0.1341,200,12/08/21 06:36:36
16,"KNN Regressor, where K = 17",3.4374,1.1937,13.2408,8.8680,0.6179,0.1409,200,12/08/21 06:36:39
17,"KNN Regressor, where K = 18",3.5022,1.1966,13.6972,9.0859,0.6054,0.1364,200,12/08/21 06:36:42
18,"KNN Regressor, where K = 19",3.5620,1.2299,14.2005,9.5197,0.5932,0.1386,200,12/08/21 06:36:46
19,"KNN Regressor, where K = 20",3.6173,1.2670,14.6902,10.0352,0.5823,0.1404,200,12/08/21 06:36:49
20,"KNN Regressor, where K = 21",3.6560,1.2869,15.0228,10.3028,0.5749,0.1398,200,12/08/21 06:36:52
21,"KNN Regressor, where K = 22",3.7337,1.2925,15.6108,10.5177,0.5575,0.1384,200,12/08/21 06:36:55
22,"KNN Regressor, where K = 23",3.7854,1.3094,16.0434,10.8974,0.5464,0.1378,200,12/08/21 06:36:58
23,"KNN Regressor, where K = 24",3.8340,1.3200,16.4416,11.1441,0.5349,0.1393,200,12/08/21 06:37:01
24,"KNN Regressor, where K = 25",3.8847,1.3316,16.8639,11.3926,0.5226,0.1413,200,12/08/21 06:37:04

In [16]:
k_test_results_4011_data = pd.read_csv(REPORT_PATH + "k-test-results_4011.csv")
k_test_results_4011_data.head(200)

,description,rmse,rmse_variance,mse,mse_variance,r2,r2_variance,num_records_analyzed,time
0,"KNN Regressor, where K = 1",2.4516,0.1245,6.0259,0.6042,0.8295,0.0110,4011,12/08/21 06:39:34
1,"KNN Regressor, where K = 2",2.2303,0.1812,5.0070,0.7926,0.8586,0.0179,4011,12/08/21 06:39:39
2,"KNN Regressor, where K = 3",2.1945,0.1714,4.8451,0.7561,0.8629,0.0188,4011,12/08/21 06:39:43
3,"KNN Regressor, where K = 4",2.2076,0.1838,4.9071,0.8121,0.8612,0.0203,4011,12/08/21 06:39:48
4,"KNN Regressor, where K = 5",2.2127,0.1888,4.9315,0.8292,0.8607,0.0199,4011,12/08/21 06:39:52
5,"KNN Regressor, where K = 6",2.2209,0.1707,4.9614,0.7554,0.8597,0.0183,4011,12/08/21 06:39:57
6,"KNN Regressor, where K = 7",2.2190,0.1763,4.9550,0.7768,0.8599,0.0187,4011,12/08/21 06:40:01
7,"KNN Regressor, where K = 8",2.2280,0.1759,4.9949,0.7784,0.8587,0.0193,4011,12/08/21 06:40:06
8,"KNN Regressor, where K = 9",2.2278,0.1771,4.9943,0.7868,0.8587,0.0196,4011,12/08/21 06:40:11
9,"KNN Regressor, where K = 10",2.2393,0.1763,5.0457,0.7875,0.8573,0.0194,4011,12/08/21 06:40:15
10,"KNN Regressor, where K = 11",2.2383,0.1893,5.0460,0.8434,0.8573,0.0209,4011,12/08/21 06:40:20
11,"KNN Regressor, where K = 12",2.2392,0.1886,5.0497,0.8430,0.8572,0.0209,4011,12/08/21 06:40:25
12,"KNN Regressor, where K = 13",2.2513,0.1920,5.1054,0.8607,0.8557,0.0212,4011,12/08/21 06:40:30
13,"KNN Regressor, where K = 14",2.2570,0.1983,5.1333,0.8951,0.8549,0.0222,4011,12/08/21 06:40:34
14,"KNN Regressor, where K = 15",2.2665,0.1948,5.1751,0.8852,0.8537,0.0221,4011,12/08/21 06:40:39
15,"KNN Regressor, where K = 16",2.2786,0.1979,5.2313,0.9029,0.8521,0.0224,4011,12/08/21 06:40:43
16,"KNN Regressor, where K = 17",2.2977,0.2052,5.3214,0.9441,0.8496,0.0233,4011,12/08/21 06:40:48
17,"KNN Regressor, where K = 18",2.3082,0.2023,5.3688,0.9357,0.8482,0.0233,4011,12/08/21 06:40:52
18,"KNN Regressor, where K = 19",2.3125,0.1988,5.3870,0.9200,0.8477,0.0228,4011,12/08/21 06:40:57
19,"KNN Regressor, where K = 20",2.3250,0.1954,5.4438,0.9095,0.8461,0.0224,4011,12/08/21 06:41:01
20,"KNN Regressor, where K = 21",2.3378,0.1964,5.5038,0.9176,0.8445,0.0222,4011,12/08/21 06:41:05
21,"KNN Regressor, where K = 22",2.3489,0.1937,5.5550,0.9108,0.8430,0.0218,4011,12/08/21 06:41:10
22,"KNN Regressor, where K = 23",2.3611,0.1949,5.6130,0.9199,0.8414,0.0220,4011,12/08/21 06:41:14
23,"KNN Regressor, where K = 24",2.3749,0.1910,5.6769,0.9063,0.8396,0.0215,4011,12/08/21 06:41:18
24,"KNN Regressor, where K = 25",2.3850,0.1919,5.7249,0.9152,0.8382,0.0219,4011,12/08/21 06:41:23

In [17]:
all_data = pd.read_csv(REPORT_PATH + "all_models_performance.csv")
all_data.head(200)

,description,rmse,rmse_variance,mse,mse_variance,r2,r2_variance,num_records_analyzed,time
0,"Random Forest Regression, where n_estimators=150",1.9053,0.5747,3.9604,2.4450,0.8840,0.0276,200,12/08/21 06:59:30
1,"KNN Regressor, where K = 4",2.8586,0.7835,8.7853,4.0419,0.7184,0.1341,200,12/08/21 06:59:33
2,Multiple Linear Regression,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,200,12/08/21 06:59:36
3,Decision Tree Regression,2.4385,1.0600,7.0700,5.0524,0.7666,0.1954,200,12/08/21 06:59:39
4,MLP Regression using Relu: 20 hidden layers wi...,0.3352,0.2973,2.0275,1.1682,0.9318,0.0445,200,12/08/21 06:59:45
5,"Random Forest Regression, where n_estimators=150",1.6265,0.3819,2.7914,1.3494,0.9291,0.0285,401,12/08/21 06:59:50
6,"KNN Regressor, where K = 4",3.2327,0.6227,10.8378,4.2826,0.7221,0.0927,401,12/08/21 06:59:53
7,Multiple Linear Regression,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,401,12/08/21 06:59:56
8,Decision Tree Regression,2.5006,1.4162,8.2585,9.8134,0.8063,0.2108,401,12/08/21 06:59:59
9,MLP Regression using Relu: 20 hidden layers wi...,0.0662,0.0412,0.6797,0.3720,0.9834,0.0071,401,12/08/21 07:00:07
10,"Random Forest Regression, where n_estimators=150",1.1860,0.1926,1.4437,0.4623,0.9611,0.0079,802,12/08/21 07:00:13
11,"KNN Regressor, where K = 4",2.6723,0.3320,7.2512,1.7190,0.7999,0.0388,802,12/08/21 07:00:16
12,Multiple Linear Regression,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,802,12/08/21 07:00:19
13,Decision Tree Regression,1.5618,0.3067,2.5332,0.9685,0.9307,0.0229,802,12/08/21 07:00:22
14,MLP Regression using Relu: 20 hidden layers wi...,0.0196,0.0101,0.0832,0.0442,0.9978,0.0009,802,12/08/21 07:00:36
15,"Random Forest Regression, where n_estimators=150",0.7888,0.0741,0.6276,0.1123,0.9824,0.0022,4011,12/08/21 07:00:49
16,"KNN Regressor, where K = 4",2.2076,0.1838,4.9071,0.8121,0.8612,0.0203,4011,12/08/21 07:00:53
17,Multiple Linear Regression,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,4011,12/08/21 07:00:57
18,Decision Tree Regression,0.9930,0.1282,1.0026,0.2516,0.9716,0.0070,4011,12/08/21 07:01:00
19,MLP Regression using Relu: 20 hidden layers wi...,0.0008,0.0006,0.0007,0.0007,1.0000,0.0000,4011,12/08/21 07:01:57
20,"Random Forest Regression, where n_estimators=150",0.6277,0.0555,0.3971,0.0682,0.9883,0.0019,8023,12/08/21 07:02:20
21,"KNN Regressor, where K = 4",2.0263,0.1399,4.1253,0.5648,0.8788,0.0097,8023,12/08/21 07:02:27
22,Multiple Linear Regression,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,8023,12/08/21 07:02:31
23,Decision Tree Regression,0.8248,0.0453,0.6823,0.0748,0.9799,0.0015,8023,12/08/21 07:02:34
24,MLP Regression using Relu: 20 hidden layers wi...,0.0006,0.0004,0.0004,0.0004,1.0000,0.0000,8023,12/08/21 07:04:29
25,"Random Forest Regression, where n_estimators=150",0.2196,0.0188,0.0486,0.0080,0.9986,0.0002,200596,12/08/21 07:31:04
26,"KNN Regressor, where K = 4",1.3434,0.0159,1.8050,0.0425,0.9477,0.0006,200596,12/08/21 08:09:10
27,Multiple Linear Regression,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,200596,12/08/21 08:09:26
28,Decision Tree Regression,0.3036,0.0224,0.0927,0.0131,0.9973,0.0003,200596,12/08/21 08:09:47
29,MLP Regression using Relu: 20 hidden layers wi...,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,200596,12/08/21 09:08:41